FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PA_HOST=0.0.0.0
ENV PA_PORT=6814
ENV PA_DATA_DIR=/app/data
ENV IMAGE_SOURCE_DIR=/app/data/images
ENV AUTO_WATCH_ENABLED=1
ENV AUTO_WATCH_DEBOUNCE_SECONDS=30
ENV AUTO_WATCH_POLLING=0
ENV PA_SCAN_HASH_MODE=off
ENV PA_SHOW_FOLDER_BTN=1
ENV PA_VIEWER_AUTO_ORIGINAL=1
ENV PA_SIDEBAR_HOVER_EXPAND=1
ENV BOOKMARK_AUTO_CHECK_WEEKDAY=0
ENV BOOKMARK_AUTO_CHECK_TIME=03:30
ENV AUTO_FAIL_PAUSE_ENABLED=1
ENV AUTO_FAIL_PAUSE_THRESHOLD=10
ENV PA_SCAN_COMMIT_BATCH=8
ENV PA_SYNC_BATCH_SIZE=8
ENV PA_METADATA_COMPACT=1
ENV PA_LOG_LEVEL=INFO

ARG PIP_INDEX_URL=https://pypi.org/simple

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --index-url "${PIP_INDEX_URL}" -r requirements.txt

COPY . .

RUN mkdir -p /app/data /app/data/images

EXPOSE 6814

CMD ["python", "-u", "run.py", "--lan"]
